#pragma line 1 "imProcessing.cpp" ::: 0
#pragma line 1 "imProcessing.cpp" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 155 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 145 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 64
#pragma line 407 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 199
#pragma line 421 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 202
#pragma line 7 "<command line>" 2 ::: 204
#pragma line 1 "<built-in>" 2 ::: 205
#pragma line 1 "imProcessing.cpp" 2 ::: 206
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 207
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 235
#pragma line 122 "/usr/include/features.h" 3 4 ::: 332
#pragma line 156 "/usr/include/features.h" 3 4 ::: 357
#pragma line 180 "/usr/include/features.h" 3 4 ::: 359
#pragma line 191 "/usr/include/features.h" 3 4 ::: 362
#pragma line 343 "/usr/include/features.h" 3 4 ::: 393
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 397
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 432
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 439
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 462
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 503
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 509
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 537
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 539
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 543
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 553
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 606
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 647
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 672
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 696
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 697
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 699
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 701
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 702
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 727
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 738
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 743
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 744
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 745
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 752
#pragma line 56 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 788
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 791
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 793
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 821
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 823
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 825
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 886
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 893
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 911
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 916
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 927
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 996
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1010
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1013
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1014
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1046
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1062
#pragma line 56 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1087
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1090
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1095
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1117
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1138
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1141
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1152
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1162
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1164
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1168
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1217
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1218
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1224
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1226
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1246
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1257
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1298
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1328
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1388
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1403
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1415
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1417
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1423
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1474
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1490
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1507
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1539
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1616
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1755
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1775
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2028
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2039
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2076
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2108
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2175
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2178
#pragma line 2 "imProcessing.cpp" 2 ::: 2180
#pragma line 1 "./imProcessing.h" 1 ::: 2181
#pragma line 1 "./ap_bmp.h" 1 ::: 2184
#pragma line 3 "./imProcessing.h" 2 ::: 2282
#pragma line 27 "./imProcessing.h" ::: 2292
#pragma line 3 "imProcessing.cpp" 2 ::: 2311
