#pragma line 1 "imProcessing.cpp" ::: -10
#pragma line 1 "imProcessing.cpp" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 155 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 145 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 54
#pragma line 407 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 189
#pragma line 421 "/home/student/Xilinx/Vivado_HLS/2016.4/common/technology/autopilot/etc/autopilot_ssdm_op.h" ::: 192
#pragma line 7 "<command line>" 2 ::: 194
#pragma line 1 "<built-in>" 2 ::: 195
#pragma line 1 "imProcessing.cpp" 2 ::: 196
#pragma line 1 "/usr/include/stdio.h" 1 3 4 ::: 197
#pragma line 1 "/usr/include/features.h" 1 3 4 ::: 225
#pragma line 122 "/usr/include/features.h" 3 4 ::: 322
#pragma line 156 "/usr/include/features.h" 3 4 ::: 347
#pragma line 180 "/usr/include/features.h" 3 4 ::: 349
#pragma line 191 "/usr/include/features.h" 3 4 ::: 352
#pragma line 343 "/usr/include/features.h" 3 4 ::: 383
#pragma line 1 "/usr/include/stdc-predef.h" 1 3 4 ::: 387
#pragma line 52 "/usr/include/stdc-predef.h" 3 4 ::: 422
#pragma line 346 "/usr/include/features.h" 2 3 4 ::: 429
#pragma line 1 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 1 3 4 ::: 452
#pragma line 49 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 493
#pragma line 80 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 499
#pragma line 106 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 517
#pragma line 119 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 523
#pragma line 131 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 527
#pragma line 147 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 529
#pragma line 165 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 533
#pragma line 192 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 543
#pragma line 252 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 596
#pragma line 305 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 637
#pragma line 346 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 662
#pragma line 410 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 3 4 ::: 686
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 687
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 689
#pragma line 411 "/usr/include/x86_64-linux-gnu/sys/cdefs.h" 2 3 4 ::: 691
#pragma line 368 "/usr/include/features.h" 2 3 4 ::: 692
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 1 3 4 ::: 717
#pragma line 1 "/usr/include/x86_64-linux-gnu/gnu/stubs-64.h" 1 3 4 ::: 728
#pragma line 11 "/usr/include/x86_64-linux-gnu/gnu/stubs.h" 2 3 4 ::: 733
#pragma line 392 "/usr/include/features.h" 2 3 4 ::: 734
#pragma line 28 "/usr/include/stdio.h" 2 3 4 ::: 735
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 742
#pragma line 56 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 778
#pragma line 34 "/usr/include/stdio.h" 2 3 4 ::: 781
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/types.h" 1 3 4 ::: 783
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 1 3 4 ::: 811
#pragma line 11 "/usr/include/x86_64-linux-gnu/bits/wordsize.h" 3 4 ::: 813
#pragma line 28 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 815
#pragma line 116 "/usr/include/x86_64-linux-gnu/bits/types.h" 3 4 ::: 876
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 1 3 4 ::: 883
#pragma line 26 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 901
#pragma line 77 "/usr/include/x86_64-linux-gnu/bits/typesizes.h" 3 4 ::: 906
#pragma line 122 "/usr/include/x86_64-linux-gnu/bits/types.h" 2 3 4 ::: 917
#pragma line 36 "/usr/include/stdio.h" 2 3 4 ::: 986
#pragma line 63 "/usr/include/stdio.h" 3 4 ::: 1000
#pragma line 74 "/usr/include/stdio.h" 3 4 ::: 1003
#pragma line 1 "/usr/include/libio.h" 1 3 4 ::: 1004
#pragma line 1 "/usr/include/_G_config.h" 1 3 4 ::: 1036
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 1 3 4 ::: 1052
#pragma line 56 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stddef.h" 3 4 ::: 1077
#pragma line 16 "/usr/include/_G_config.h" 2 3 4 ::: 1080
#pragma line 1 "/usr/include/wchar.h" 1 3 4 ::: 1085
#pragma line 81 "/usr/include/wchar.h" 3 4 ::: 1107
#pragma line 900 "/usr/include/wchar.h" 3 4 ::: 1128
#pragma line 21 "/usr/include/_G_config.h" 2 3 4 ::: 1131
#pragma line 45 "/usr/include/_G_config.h" 3 4 ::: 1142
#pragma line 32 "/usr/include/libio.h" 2 3 4 ::: 1152
#pragma line 47 "/usr/include/libio.h" 3 4 ::: 1154
#pragma line 1 "/home/student/Xilinx/Vivado_HLS/2016.4/lnx64/tools/clang/bin/../lib/clang/3.1/include/stdarg.h" 1 3 4 ::: 1158
#pragma line 50 "/usr/include/libio.h" 2 3 4 ::: 1207
#pragma line 86 "/usr/include/libio.h" 3 4 ::: 1208
#pragma line 124 "/usr/include/libio.h" 3 4 ::: 1214
#pragma line 144 "/usr/include/libio.h" 3 4 ::: 1216
#pragma line 173 "/usr/include/libio.h" 3 4 ::: 1236
#pragma line 241 "/usr/include/libio.h" 3 4 ::: 1247
#pragma line 289 "/usr/include/libio.h" 3 4 ::: 1288
#pragma line 329 "/usr/include/libio.h" 3 4 ::: 1318
#pragma line 429 "/usr/include/libio.h" 3 4 ::: 1378
#pragma line 459 "/usr/include/libio.h" 3 4 ::: 1393
#pragma line 521 "/usr/include/libio.h" 3 4 ::: 1405
#pragma line 75 "/usr/include/stdio.h" 2 3 4 ::: 1407
#pragma line 90 "/usr/include/stdio.h" 3 4 ::: 1413
#pragma line 150 "/usr/include/stdio.h" 3 4 ::: 1464
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/stdio_lim.h" 1 3 4 ::: 1480
#pragma line 165 "/usr/include/stdio.h" 2 3 4 ::: 1497
#pragma line 205 "/usr/include/stdio.h" 3 4 ::: 1529
#pragma line 297 "/usr/include/stdio.h" 3 4 ::: 1606
#pragma line 467 "/usr/include/stdio.h" 3 4 ::: 1745
#pragma line 527 "/usr/include/stdio.h" 3 4 ::: 1765
#pragma line 794 "/usr/include/stdio.h" 3 4 ::: 2018
#pragma line 818 "/usr/include/stdio.h" 3 4 ::: 2029
#pragma line 1 "/usr/include/x86_64-linux-gnu/bits/sys_errlist.h" 1 3 4 ::: 2066
#pragma line 854 "/usr/include/stdio.h" 2 3 4 ::: 2098
#pragma line 930 "/usr/include/stdio.h" 3 4 ::: 2165
#pragma line 942 "/usr/include/stdio.h" 3 4 ::: 2168
#pragma line 2 "imProcessing.cpp" 2 ::: 2170
#pragma line 1 "./imProcessing.h" 1 ::: 2171
#pragma line 1 "./ap_bmp.h" 1 ::: 2174
#pragma line 3 "./imProcessing.h" 2 ::: 2272
#pragma line 27 "./imProcessing.h" ::: 2282
#pragma line 3 "imProcessing.cpp" 2 ::: 2301
