// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "imGrayScale.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic imGrayScale::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic imGrayScale::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<31> imGrayScale::ap_ST_fsm_state1 = "1";
const sc_lv<31> imGrayScale::ap_ST_fsm_state2 = "10";
const sc_lv<31> imGrayScale::ap_ST_fsm_state3 = "100";
const sc_lv<31> imGrayScale::ap_ST_fsm_state4 = "1000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state5 = "10000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state6 = "100000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state7 = "1000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state8 = "10000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state9 = "100000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state10 = "1000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state11 = "10000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state12 = "100000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state15 = "100000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state16 = "1000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state17 = "10000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state18 = "100000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state19 = "1000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state20 = "10000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state21 = "100000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state22 = "1000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state23 = "10000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state24 = "100000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state25 = "1000000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state26 = "10000000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state27 = "100000000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state28 = "1000000000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state29 = "10000000000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state30 = "100000000000000000000000000000";
const sc_lv<31> imGrayScale::ap_ST_fsm_state31 = "1000000000000000000000000000000";
const sc_lv<32> imGrayScale::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> imGrayScale::ap_const_lv1_1 = "1";
const sc_lv<32> imGrayScale::ap_const_lv32_11 = "10001";
const sc_lv<32> imGrayScale::ap_const_lv32_16 = "10110";
const sc_lv<32> imGrayScale::ap_const_lv32_1 = "1";
const sc_lv<32> imGrayScale::ap_const_lv32_2 = "10";
const sc_lv<1> imGrayScale::ap_const_lv1_0 = "0";
const sc_lv<32> imGrayScale::ap_const_lv32_5 = "101";
const sc_lv<32> imGrayScale::ap_const_lv32_6 = "110";
const sc_lv<32> imGrayScale::ap_const_lv32_B = "1011";
const sc_lv<32> imGrayScale::ap_const_lv32_10 = "10000";
const sc_lv<32> imGrayScale::ap_const_lv32_1B = "11011";
const sc_lv<32> imGrayScale::ap_const_lv32_1C = "11100";
const sc_lv<32> imGrayScale::ap_const_lv32_1D = "11101";
const sc_lv<31> imGrayScale::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<42> imGrayScale::ap_const_lv42_0 = "000000000000000000000000000000000000000000";
const sc_lv<32> imGrayScale::ap_const_lv32_1E = "11110";
const sc_lv<32> imGrayScale::ap_const_lv32_3 = "11";
const sc_lv<32> imGrayScale::ap_const_lv32_4 = "100";
const sc_lv<32> imGrayScale::ap_const_lv32_12 = "10010";
const sc_lv<32> imGrayScale::ap_const_lv32_17 = "10111";
const sc_lv<64> imGrayScale::ap_const_lv64_3FBD2F1A9FBE76C9 = "11111110111101001011110001101010011111101111100111011011001001";
const sc_lv<64> imGrayScale::ap_const_lv64_3FE2C8B439581062 = "11111111100010110010001011010000111001010110000001000001100010";
const sc_lv<32> imGrayScale::ap_const_lv32_C = "1100";
const sc_lv<64> imGrayScale::ap_const_lv64_3FD322D0E5604189 = "11111111010011001000101101000011100101011000000100000110001001";
const sc_lv<42> imGrayScale::ap_const_lv42_4B0 = "10010110000";
const sc_lv<31> imGrayScale::ap_const_lv31_1 = "1";
const sc_lv<32> imGrayScale::ap_const_lv32_8 = "1000";
const sc_lv<32> imGrayScale::ap_const_lv32_F = "1111";
const sc_lv<32> imGrayScale::ap_const_lv32_34 = "110100";
const sc_lv<32> imGrayScale::ap_const_lv32_3E = "111110";
const sc_lv<12> imGrayScale::ap_const_lv12_C01 = "110000000001";
const sc_lv<11> imGrayScale::ap_const_lv11_3FF = "1111111111";
const sc_lv<32> imGrayScale::ap_const_lv32_3B = "111011";

imGrayScale::imGrayScale(sc_module_name name) : sc_module(name), mVcdFile(0) {
    imTemplateMatchinbkb_U1 = new imTemplateMatchinbkb<1,5,64,64,64>("imTemplateMatchinbkb_U1");
    imTemplateMatchinbkb_U1->clk(ap_clk);
    imTemplateMatchinbkb_U1->reset(ap_rst);
    imTemplateMatchinbkb_U1->din0(grp_fu_151_p0);
    imTemplateMatchinbkb_U1->din1(grp_fu_151_p1);
    imTemplateMatchinbkb_U1->ce(ap_var_for_const0);
    imTemplateMatchinbkb_U1->dout(grp_fu_151_p2);
    imTemplateMatchincud_U2 = new imTemplateMatchincud<1,6,64,64,64>("imTemplateMatchincud_U2");
    imTemplateMatchincud_U2->clk(ap_clk);
    imTemplateMatchincud_U2->reset(ap_rst);
    imTemplateMatchincud_U2->din0(grp_fu_155_p0);
    imTemplateMatchincud_U2->din1(grp_fu_155_p1);
    imTemplateMatchincud_U2->ce(ap_var_for_const0);
    imTemplateMatchincud_U2->dout(grp_fu_155_p2);
    imTemplateMatchincud_U3 = new imTemplateMatchincud<1,6,64,64,64>("imTemplateMatchincud_U3");
    imTemplateMatchincud_U3->clk(ap_clk);
    imTemplateMatchincud_U3->reset(ap_rst);
    imTemplateMatchincud_U3->din0(tmp_24_reg_470);
    imTemplateMatchincud_U3->din1(ap_var_for_const1);
    imTemplateMatchincud_U3->ce(ap_var_for_const0);
    imTemplateMatchincud_U3->dout(grp_fu_160_p2);
    imTemplateMatchindEe_U4 = new imTemplateMatchindEe<1,6,32,64>("imTemplateMatchindEe_U4");
    imTemplateMatchindEe_U4->clk(ap_clk);
    imTemplateMatchindEe_U4->reset(ap_rst);
    imTemplateMatchindEe_U4->din0(grp_fu_166_p0);
    imTemplateMatchindEe_U4->ce(ap_var_for_const0);
    imTemplateMatchindEe_U4->dout(grp_fu_166_p1);
    imTemplateMatchindEe_U5 = new imTemplateMatchindEe<1,6,32,64>("imTemplateMatchindEe_U5");
    imTemplateMatchindEe_U5->clk(ap_clk);
    imTemplateMatchindEe_U5->reset(ap_rst);
    imTemplateMatchindEe_U5->din0(grp_fu_169_p0);
    imTemplateMatchindEe_U5->ce(ap_var_for_const0);
    imTemplateMatchindEe_U5->dout(grp_fu_169_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state17);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state18);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state19);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state23);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state24);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state28);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state29);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state30);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state31);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_192_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_fu_192_p2 );

    SC_METHOD(thread_col_4_fu_212_p2);
    sensitive << ( col_reg_140 );

    SC_METHOD(thread_col_cast_fu_203_p1);
    sensitive << ( col_reg_140 );

    SC_METHOD(thread_grp_fu_151_p0);
    sensitive << ( reg_172 );
    sensitive << ( tmp_26_reg_490 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_151_p1);
    sensitive << ( reg_172 );
    sensitive << ( tmp_25_reg_485 );
    sensitive << ( ap_CS_fsm_state19 );
    sensitive << ( ap_CS_fsm_state24 );

    SC_METHOD(thread_grp_fu_155_p0);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( tmp_21_reg_465 );
    sensitive << ( tmp_27_reg_480 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_155_p1);
    sensitive << ( ap_CS_fsm_state18 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_166_p0);
    sensitive << ( tmp_20_cast_fu_256_p1 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( tmp_29_cast_fu_264_p1 );

    SC_METHOD(thread_grp_fu_169_p0);
    sensitive << ( tmp_23_cast_reg_445 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_imINPUT_address0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( tmp_33_cast_fu_227_p1 );

    SC_METHOD(thread_imINPUT_ce0);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_imOUTPUT_address0);
    sensitive << ( tmp_33_cast_reg_430 );
    sensitive << ( ap_CS_fsm_state30 );

    SC_METHOD(thread_imOUTPUT_ce0);
    sensitive << ( ap_CS_fsm_state30 );
    sensitive << ( ap_CS_fsm_state31 );

    SC_METHOD(thread_imOUTPUT_d0);
    sensitive << ( result_V_reg_506 );
    sensitive << ( ap_CS_fsm_state30 );

    SC_METHOD(thread_imOUTPUT_we0);
    sensitive << ( ap_CS_fsm_state30 );

    SC_METHOD(thread_isNeg_fu_306_p3);
    sensitive << ( sh_assign_fu_300_p2 );

    SC_METHOD(thread_loc_V_2_fu_282_p1);
    sensitive << ( p_Val2_s_fu_268_p1 );

    SC_METHOD(thread_next_mul_fu_182_p2);
    sensitive << ( phi_mul_reg_129 );

    SC_METHOD(thread_p_Result_s_fu_286_p3);
    sensitive << ( loc_V_2_reg_501 );

    SC_METHOD(thread_p_Val2_s_fu_268_p1);
    sensitive << ( grp_fu_151_p2 );

    SC_METHOD(thread_result_V_fu_377_p3);
    sensitive << ( isNeg_fu_306_p3 );
    sensitive << ( tmp_30_fu_363_p1 );
    sensitive << ( tmp_31_fu_367_p4 );

    SC_METHOD(thread_row_4_fu_197_p2);
    sensitive << ( row_reg_118 );

    SC_METHOD(thread_row_cast_fu_188_p1);
    sensitive << ( row_reg_118 );

    SC_METHOD(thread_sh_assign_2_cast_fu_331_p1);
    sensitive << ( sh_assign_2_fu_323_p3 );

    SC_METHOD(thread_sh_assign_2_fu_323_p3);
    sensitive << ( sh_assign_fu_300_p2 );
    sensitive << ( isNeg_fu_306_p3 );
    sensitive << ( tmp_i_i_cast_fu_319_p1 );

    SC_METHOD(thread_sh_assign_fu_300_p2);
    sensitive << ( tmp_i_i_i_cast3_fu_297_p1 );

    SC_METHOD(thread_tmp_18_fu_207_p2);
    sensitive << ( imWidth );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_cast_fu_203_p1 );

    SC_METHOD(thread_tmp_20_cast_fu_256_p1);
    sensitive << ( tmp_39_reg_440 );

    SC_METHOD(thread_tmp_23_fu_222_p2);
    sensitive << ( tmp_37_reg_404 );
    sensitive << ( tmp_38_fu_218_p1 );

    SC_METHOD(thread_tmp_29_cast_fu_264_p1);
    sensitive << ( tmp_28_cast_reg_450 );

    SC_METHOD(thread_tmp_30_fu_363_p1);
    sensitive << ( tmp_42_fu_355_p3 );

    SC_METHOD(thread_tmp_31_fu_367_p4);
    sensitive << ( tmp_62_i_i_fu_349_p2 );

    SC_METHOD(thread_tmp_33_cast_fu_227_p1);
    sensitive << ( tmp_23_fu_222_p2 );

    SC_METHOD(thread_tmp_37_fu_178_p1);
    sensitive << ( phi_mul_reg_129 );

    SC_METHOD(thread_tmp_38_fu_218_p1);
    sensitive << ( col_reg_140 );

    SC_METHOD(thread_tmp_39_fu_232_p1);
    sensitive << ( imINPUT_q0 );

    SC_METHOD(thread_tmp_42_fu_355_p3);
    sensitive << ( tmp_61_i_i_fu_343_p2 );

    SC_METHOD(thread_tmp_60_i_i_cast_fu_339_p1);
    sensitive << ( sh_assign_2_cast_fu_331_p1 );

    SC_METHOD(thread_tmp_60_i_i_fu_335_p1);
    sensitive << ( sh_assign_2_cast_fu_331_p1 );

    SC_METHOD(thread_tmp_61_i_i_fu_343_p2);
    sensitive << ( p_Result_s_fu_286_p3 );
    sensitive << ( tmp_60_i_i_cast_fu_339_p1 );

    SC_METHOD(thread_tmp_62_i_i_fu_349_p2);
    sensitive << ( tmp_i_i_fu_293_p1 );
    sensitive << ( tmp_60_i_i_fu_335_p1 );

    SC_METHOD(thread_tmp_fu_192_p2);
    sensitive << ( imHeight );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_cast_fu_188_p1 );

    SC_METHOD(thread_tmp_i_i_16_fu_314_p2);
    sensitive << ( loc_V_reg_495 );

    SC_METHOD(thread_tmp_i_i_cast_fu_319_p1);
    sensitive << ( tmp_i_i_16_fu_314_p2 );

    SC_METHOD(thread_tmp_i_i_fu_293_p1);
    sensitive << ( p_Result_s_fu_286_p3 );

    SC_METHOD(thread_tmp_i_i_i_cast3_fu_297_p1);
    sensitive << ( loc_V_reg_495 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( tmp_18_fu_207_p2 );
    sensitive << ( tmp_fu_192_p2 );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000000000000000000000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "imGrayScale_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, imINPUT_address0, "(port)imINPUT_address0");
    sc_trace(mVcdFile, imINPUT_ce0, "(port)imINPUT_ce0");
    sc_trace(mVcdFile, imINPUT_q0, "(port)imINPUT_q0");
    sc_trace(mVcdFile, imOUTPUT_address0, "(port)imOUTPUT_address0");
    sc_trace(mVcdFile, imOUTPUT_ce0, "(port)imOUTPUT_ce0");
    sc_trace(mVcdFile, imOUTPUT_we0, "(port)imOUTPUT_we0");
    sc_trace(mVcdFile, imOUTPUT_d0, "(port)imOUTPUT_d0");
    sc_trace(mVcdFile, imHeight, "(port)imHeight");
    sc_trace(mVcdFile, imWidth, "(port)imWidth");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, grp_fu_155_p2, "grp_fu_155_p2");
    sc_trace(mVcdFile, reg_172, "reg_172");
    sc_trace(mVcdFile, ap_CS_fsm_state18, "ap_CS_fsm_state18");
    sc_trace(mVcdFile, ap_CS_fsm_state23, "ap_CS_fsm_state23");
    sc_trace(mVcdFile, tmp_37_fu_178_p1, "tmp_37_fu_178_p1");
    sc_trace(mVcdFile, tmp_37_reg_404, "tmp_37_reg_404");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, next_mul_fu_182_p2, "next_mul_fu_182_p2");
    sc_trace(mVcdFile, next_mul_reg_409, "next_mul_reg_409");
    sc_trace(mVcdFile, row_4_fu_197_p2, "row_4_fu_197_p2");
    sc_trace(mVcdFile, row_4_reg_417, "row_4_reg_417");
    sc_trace(mVcdFile, col_4_fu_212_p2, "col_4_fu_212_p2");
    sc_trace(mVcdFile, col_4_reg_425, "col_4_reg_425");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_33_cast_fu_227_p1, "tmp_33_cast_fu_227_p1");
    sc_trace(mVcdFile, tmp_33_cast_reg_430, "tmp_33_cast_reg_430");
    sc_trace(mVcdFile, tmp_18_fu_207_p2, "tmp_18_fu_207_p2");
    sc_trace(mVcdFile, tmp_39_fu_232_p1, "tmp_39_fu_232_p1");
    sc_trace(mVcdFile, tmp_39_reg_440, "tmp_39_reg_440");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_23_cast_reg_445, "tmp_23_cast_reg_445");
    sc_trace(mVcdFile, tmp_28_cast_reg_450, "tmp_28_cast_reg_450");
    sc_trace(mVcdFile, tmp_20_cast_fu_256_p1, "tmp_20_cast_fu_256_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_166_p1, "grp_fu_166_p1");
    sc_trace(mVcdFile, tmp_21_reg_465, "tmp_21_reg_465");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, grp_fu_169_p1, "grp_fu_169_p1");
    sc_trace(mVcdFile, tmp_24_reg_470, "tmp_24_reg_470");
    sc_trace(mVcdFile, tmp_29_cast_fu_264_p1, "tmp_29_cast_fu_264_p1");
    sc_trace(mVcdFile, tmp_27_reg_480, "tmp_27_reg_480");
    sc_trace(mVcdFile, ap_CS_fsm_state17, "ap_CS_fsm_state17");
    sc_trace(mVcdFile, grp_fu_160_p2, "grp_fu_160_p2");
    sc_trace(mVcdFile, tmp_25_reg_485, "tmp_25_reg_485");
    sc_trace(mVcdFile, grp_fu_151_p2, "grp_fu_151_p2");
    sc_trace(mVcdFile, tmp_26_reg_490, "tmp_26_reg_490");
    sc_trace(mVcdFile, loc_V_reg_495, "loc_V_reg_495");
    sc_trace(mVcdFile, ap_CS_fsm_state28, "ap_CS_fsm_state28");
    sc_trace(mVcdFile, loc_V_2_fu_282_p1, "loc_V_2_fu_282_p1");
    sc_trace(mVcdFile, loc_V_2_reg_501, "loc_V_2_reg_501");
    sc_trace(mVcdFile, result_V_fu_377_p3, "result_V_fu_377_p3");
    sc_trace(mVcdFile, result_V_reg_506, "result_V_reg_506");
    sc_trace(mVcdFile, ap_CS_fsm_state29, "ap_CS_fsm_state29");
    sc_trace(mVcdFile, ap_CS_fsm_state30, "ap_CS_fsm_state30");
    sc_trace(mVcdFile, row_reg_118, "row_reg_118");
    sc_trace(mVcdFile, phi_mul_reg_129, "phi_mul_reg_129");
    sc_trace(mVcdFile, col_reg_140, "col_reg_140");
    sc_trace(mVcdFile, tmp_fu_192_p2, "tmp_fu_192_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state31, "ap_CS_fsm_state31");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, grp_fu_151_p0, "grp_fu_151_p0");
    sc_trace(mVcdFile, grp_fu_151_p1, "grp_fu_151_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state19, "ap_CS_fsm_state19");
    sc_trace(mVcdFile, ap_CS_fsm_state24, "ap_CS_fsm_state24");
    sc_trace(mVcdFile, grp_fu_155_p0, "grp_fu_155_p0");
    sc_trace(mVcdFile, grp_fu_155_p1, "grp_fu_155_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_fu_166_p0, "grp_fu_166_p0");
    sc_trace(mVcdFile, grp_fu_169_p0, "grp_fu_169_p0");
    sc_trace(mVcdFile, row_cast_fu_188_p1, "row_cast_fu_188_p1");
    sc_trace(mVcdFile, col_cast_fu_203_p1, "col_cast_fu_203_p1");
    sc_trace(mVcdFile, tmp_38_fu_218_p1, "tmp_38_fu_218_p1");
    sc_trace(mVcdFile, tmp_23_fu_222_p2, "tmp_23_fu_222_p2");
    sc_trace(mVcdFile, p_Val2_s_fu_268_p1, "p_Val2_s_fu_268_p1");
    sc_trace(mVcdFile, p_Result_s_fu_286_p3, "p_Result_s_fu_286_p3");
    sc_trace(mVcdFile, tmp_i_i_i_cast3_fu_297_p1, "tmp_i_i_i_cast3_fu_297_p1");
    sc_trace(mVcdFile, sh_assign_fu_300_p2, "sh_assign_fu_300_p2");
    sc_trace(mVcdFile, tmp_i_i_16_fu_314_p2, "tmp_i_i_16_fu_314_p2");
    sc_trace(mVcdFile, isNeg_fu_306_p3, "isNeg_fu_306_p3");
    sc_trace(mVcdFile, tmp_i_i_cast_fu_319_p1, "tmp_i_i_cast_fu_319_p1");
    sc_trace(mVcdFile, sh_assign_2_fu_323_p3, "sh_assign_2_fu_323_p3");
    sc_trace(mVcdFile, sh_assign_2_cast_fu_331_p1, "sh_assign_2_cast_fu_331_p1");
    sc_trace(mVcdFile, tmp_60_i_i_cast_fu_339_p1, "tmp_60_i_i_cast_fu_339_p1");
    sc_trace(mVcdFile, tmp_i_i_fu_293_p1, "tmp_i_i_fu_293_p1");
    sc_trace(mVcdFile, tmp_60_i_i_fu_335_p1, "tmp_60_i_i_fu_335_p1");
    sc_trace(mVcdFile, tmp_61_i_i_fu_343_p2, "tmp_61_i_i_fu_343_p2");
    sc_trace(mVcdFile, tmp_42_fu_355_p3, "tmp_42_fu_355_p3");
    sc_trace(mVcdFile, tmp_62_i_i_fu_349_p2, "tmp_62_i_i_fu_349_p2");
    sc_trace(mVcdFile, tmp_30_fu_363_p1, "tmp_30_fu_363_p1");
    sc_trace(mVcdFile, tmp_31_fu_367_p4, "tmp_31_fu_367_p4");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

imGrayScale::~imGrayScale() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete imTemplateMatchinbkb_U1;
    delete imTemplateMatchincud_U2;
    delete imTemplateMatchincud_U3;
    delete imTemplateMatchindEe_U4;
    delete imTemplateMatchindEe_U5;
}

void imGrayScale::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void imGrayScale::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3FD322D0E5604189;
}

void imGrayScale::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read()))) {
        col_reg_140 = col_4_reg_425.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
                !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_192_p2.read()))) {
        col_reg_140 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_18_fu_207_p2.read(), ap_const_lv1_0))) {
        phi_mul_reg_129 = next_mul_reg_409.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        phi_mul_reg_129 = ap_const_lv42_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(tmp_18_fu_207_p2.read(), ap_const_lv1_0))) {
        row_reg_118 = row_4_reg_417.read();
    } else if ((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
                !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0))) {
        row_reg_118 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()))) {
        col_4_reg_425 = col_4_fu_212_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state28.read()))) {
        loc_V_2_reg_501 = loc_V_2_fu_282_p1.read();
        loc_V_reg_495 = p_Val2_s_fu_268_p1.read().range(62, 52);
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        next_mul_reg_409 = next_mul_fu_182_p2.read();
        row_4_reg_417 = row_4_fu_197_p2.read();
        tmp_37_reg_404 = tmp_37_fu_178_p1.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read())) || (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read())))) {
        reg_172 = grp_fu_155_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state29.read()))) {
        result_V_reg_506 = result_V_fu_377_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        tmp_21_reg_465 = grp_fu_166_p1.read();
        tmp_24_reg_470 = grp_fu_169_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        tmp_23_cast_reg_445 = imINPUT_q0.read().range(15, 8);
        tmp_28_cast_reg_450 = imINPUT_q0.read().range(23, 16);
        tmp_39_reg_440 = tmp_39_fu_232_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        tmp_25_reg_485 = grp_fu_160_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state23.read()))) {
        tmp_26_reg_490 = grp_fu_151_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state17.read()))) {
        tmp_27_reg_480 = grp_fu_166_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read()) && !esl_seteq<1,1,1>(tmp_18_fu_207_p2.read(), ap_const_lv1_0))) {
        tmp_33_cast_reg_430 = tmp_33_cast_fu_227_p1.read();
    }
}

void imGrayScale::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void imGrayScale::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read().range(11, 11);
}

void imGrayScale::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void imGrayScale::thread_ap_CS_fsm_state17() {
    ap_CS_fsm_state17 = ap_CS_fsm.read().range(16, 16);
}

void imGrayScale::thread_ap_CS_fsm_state18() {
    ap_CS_fsm_state18 = ap_CS_fsm.read().range(17, 17);
}

void imGrayScale::thread_ap_CS_fsm_state19() {
    ap_CS_fsm_state19 = ap_CS_fsm.read().range(18, 18);
}

void imGrayScale::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void imGrayScale::thread_ap_CS_fsm_state23() {
    ap_CS_fsm_state23 = ap_CS_fsm.read().range(22, 22);
}

void imGrayScale::thread_ap_CS_fsm_state24() {
    ap_CS_fsm_state24 = ap_CS_fsm.read().range(23, 23);
}

void imGrayScale::thread_ap_CS_fsm_state28() {
    ap_CS_fsm_state28 = ap_CS_fsm.read().range(27, 27);
}

void imGrayScale::thread_ap_CS_fsm_state29() {
    ap_CS_fsm_state29 = ap_CS_fsm.read().range(28, 28);
}

void imGrayScale::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void imGrayScale::thread_ap_CS_fsm_state30() {
    ap_CS_fsm_state30 = ap_CS_fsm.read().range(29, 29);
}

void imGrayScale::thread_ap_CS_fsm_state31() {
    ap_CS_fsm_state31 = ap_CS_fsm.read().range(30, 30);
}

void imGrayScale::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void imGrayScale::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void imGrayScale::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void imGrayScale::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void imGrayScale::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1)) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_192_p2.read())))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void imGrayScale::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void imGrayScale::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_192_p2.read()))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void imGrayScale::thread_col_4_fu_212_p2() {
    col_4_fu_212_p2 = (!col_reg_140.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(col_reg_140.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void imGrayScale::thread_col_cast_fu_203_p1() {
    col_cast_fu_203_p1 = esl_zext<32,31>(col_reg_140.read());
}

void imGrayScale::thread_grp_fu_151_p0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        grp_fu_151_p0 = tmp_26_reg_490.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        grp_fu_151_p0 = reg_172.read();
    } else {
        grp_fu_151_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imGrayScale::thread_grp_fu_151_p1() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state24.read()))) {
        grp_fu_151_p1 = reg_172.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state19.read()))) {
        grp_fu_151_p1 = tmp_25_reg_485.read();
    } else {
        grp_fu_151_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imGrayScale::thread_grp_fu_155_p0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        grp_fu_155_p0 = tmp_27_reg_480.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        grp_fu_155_p0 = tmp_21_reg_465.read();
    } else {
        grp_fu_155_p0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imGrayScale::thread_grp_fu_155_p1() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state18.read()))) {
        grp_fu_155_p1 = ap_const_lv64_3FE2C8B439581062;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        grp_fu_155_p1 = ap_const_lv64_3FBD2F1A9FBE76C9;
    } else {
        grp_fu_155_p1 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imGrayScale::thread_grp_fu_166_p0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read()))) {
        grp_fu_166_p0 = tmp_29_cast_fu_264_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
        grp_fu_166_p0 = tmp_20_cast_fu_256_p1.read();
    } else {
        grp_fu_166_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void imGrayScale::thread_grp_fu_169_p0() {
    grp_fu_169_p0 = esl_zext<32,8>(tmp_23_cast_reg_445.read());
}

void imGrayScale::thread_imINPUT_address0() {
    imINPUT_address0 =  (sc_lv<21>) (tmp_33_cast_fu_227_p1.read());
}

void imGrayScale::thread_imINPUT_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read())))) {
        imINPUT_ce0 = ap_const_logic_1;
    } else {
        imINPUT_ce0 = ap_const_logic_0;
    }
}

void imGrayScale::thread_imOUTPUT_address0() {
    imOUTPUT_address0 =  (sc_lv<21>) (tmp_33_cast_reg_430.read());
}

void imGrayScale::thread_imOUTPUT_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state31.read())))) {
        imOUTPUT_ce0 = ap_const_logic_1;
    } else {
        imOUTPUT_ce0 = ap_const_logic_0;
    }
}

void imGrayScale::thread_imOUTPUT_d0() {
    imOUTPUT_d0 = esl_concat<24,8>(esl_concat<16,8>(esl_concat<8,8>(result_V_reg_506.read(), result_V_reg_506.read()), result_V_reg_506.read()), result_V_reg_506.read());
}

void imGrayScale::thread_imOUTPUT_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state30.read())))) {
        imOUTPUT_we0 = ap_const_logic_1;
    } else {
        imOUTPUT_we0 = ap_const_logic_0;
    }
}

void imGrayScale::thread_isNeg_fu_306_p3() {
    isNeg_fu_306_p3 = sh_assign_fu_300_p2.read().range(11, 11);
}

void imGrayScale::thread_loc_V_2_fu_282_p1() {
    loc_V_2_fu_282_p1 = p_Val2_s_fu_268_p1.read().range(52-1, 0);
}

void imGrayScale::thread_next_mul_fu_182_p2() {
    next_mul_fu_182_p2 = (!ap_const_lv42_4B0.is_01() || !phi_mul_reg_129.read().is_01())? sc_lv<42>(): (sc_biguint<42>(ap_const_lv42_4B0) + sc_biguint<42>(phi_mul_reg_129.read()));
}

void imGrayScale::thread_p_Result_s_fu_286_p3() {
    p_Result_s_fu_286_p3 = esl_concat<1,52>(ap_const_lv1_1, loc_V_2_reg_501.read());
}

void imGrayScale::thread_p_Val2_s_fu_268_p1() {
    p_Val2_s_fu_268_p1 = grp_fu_151_p2.read();
}

void imGrayScale::thread_result_V_fu_377_p3() {
    result_V_fu_377_p3 = (!isNeg_fu_306_p3.read()[0].is_01())? sc_lv<8>(): ((isNeg_fu_306_p3.read()[0].to_bool())? tmp_30_fu_363_p1.read(): tmp_31_fu_367_p4.read());
}

void imGrayScale::thread_row_4_fu_197_p2() {
    row_4_fu_197_p2 = (!ap_const_lv31_1.is_01() || !row_reg_118.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(row_reg_118.read()));
}

void imGrayScale::thread_row_cast_fu_188_p1() {
    row_cast_fu_188_p1 = esl_zext<32,31>(row_reg_118.read());
}

void imGrayScale::thread_sh_assign_2_cast_fu_331_p1() {
    sh_assign_2_cast_fu_331_p1 = esl_sext<32,12>(sh_assign_2_fu_323_p3.read());
}

void imGrayScale::thread_sh_assign_2_fu_323_p3() {
    sh_assign_2_fu_323_p3 = (!isNeg_fu_306_p3.read()[0].is_01())? sc_lv<12>(): ((isNeg_fu_306_p3.read()[0].to_bool())? tmp_i_i_cast_fu_319_p1.read(): sh_assign_fu_300_p2.read());
}

void imGrayScale::thread_sh_assign_fu_300_p2() {
    sh_assign_fu_300_p2 = (!ap_const_lv12_C01.is_01() || !tmp_i_i_i_cast3_fu_297_p1.read().is_01())? sc_lv<12>(): (sc_bigint<12>(ap_const_lv12_C01) + sc_biguint<12>(tmp_i_i_i_cast3_fu_297_p1.read()));
}

void imGrayScale::thread_tmp_18_fu_207_p2() {
    tmp_18_fu_207_p2 = (!col_cast_fu_203_p1.read().is_01() || !imWidth.read().is_01())? sc_lv<1>(): (sc_bigint<32>(col_cast_fu_203_p1.read()) < sc_bigint<32>(imWidth.read()));
}

void imGrayScale::thread_tmp_20_cast_fu_256_p1() {
    tmp_20_cast_fu_256_p1 = esl_zext<32,8>(tmp_39_reg_440.read());
}

void imGrayScale::thread_tmp_23_fu_222_p2() {
    tmp_23_fu_222_p2 = (!tmp_37_reg_404.read().is_01() || !tmp_38_fu_218_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_37_reg_404.read()) + sc_biguint<22>(tmp_38_fu_218_p1.read()));
}

void imGrayScale::thread_tmp_29_cast_fu_264_p1() {
    tmp_29_cast_fu_264_p1 = esl_zext<32,8>(tmp_28_cast_reg_450.read());
}

void imGrayScale::thread_tmp_30_fu_363_p1() {
    tmp_30_fu_363_p1 = esl_zext<8,1>(tmp_42_fu_355_p3.read());
}

void imGrayScale::thread_tmp_31_fu_367_p4() {
    tmp_31_fu_367_p4 = tmp_62_i_i_fu_349_p2.read().range(59, 52);
}

void imGrayScale::thread_tmp_33_cast_fu_227_p1() {
    tmp_33_cast_fu_227_p1 = esl_zext<64,22>(tmp_23_fu_222_p2.read());
}

void imGrayScale::thread_tmp_37_fu_178_p1() {
    tmp_37_fu_178_p1 = phi_mul_reg_129.read().range(22-1, 0);
}

void imGrayScale::thread_tmp_38_fu_218_p1() {
    tmp_38_fu_218_p1 = col_reg_140.read().range(22-1, 0);
}

void imGrayScale::thread_tmp_39_fu_232_p1() {
    tmp_39_fu_232_p1 = imINPUT_q0.read().range(8-1, 0);
}

void imGrayScale::thread_tmp_42_fu_355_p3() {
    tmp_42_fu_355_p3 = tmp_61_i_i_fu_343_p2.read().range(52, 52);
}

void imGrayScale::thread_tmp_60_i_i_cast_fu_339_p1() {
    tmp_60_i_i_cast_fu_339_p1 = esl_zext<53,32>(sh_assign_2_cast_fu_331_p1.read());
}

void imGrayScale::thread_tmp_60_i_i_fu_335_p1() {
    tmp_60_i_i_fu_335_p1 = esl_zext<112,32>(sh_assign_2_cast_fu_331_p1.read());
}

void imGrayScale::thread_tmp_61_i_i_fu_343_p2() {
    tmp_61_i_i_fu_343_p2 = (!tmp_60_i_i_cast_fu_339_p1.read().is_01())? sc_lv<53>(): p_Result_s_fu_286_p3.read() >> (unsigned short)tmp_60_i_i_cast_fu_339_p1.read().to_uint();
}

void imGrayScale::thread_tmp_62_i_i_fu_349_p2() {
    tmp_62_i_i_fu_349_p2 = (!tmp_60_i_i_fu_335_p1.read().is_01())? sc_lv<112>(): tmp_i_i_fu_293_p1.read() << (unsigned short)tmp_60_i_i_fu_335_p1.read().to_uint();
}

void imGrayScale::thread_tmp_fu_192_p2() {
    tmp_fu_192_p2 = (!row_cast_fu_188_p1.read().is_01() || !imHeight.read().is_01())? sc_lv<1>(): (sc_bigint<32>(row_cast_fu_188_p1.read()) < sc_bigint<32>(imHeight.read()));
}

void imGrayScale::thread_tmp_i_i_16_fu_314_p2() {
    tmp_i_i_16_fu_314_p2 = (!ap_const_lv11_3FF.is_01() || !loc_V_reg_495.read().is_01())? sc_lv<11>(): (sc_biguint<11>(ap_const_lv11_3FF) - sc_biguint<11>(loc_V_reg_495.read()));
}

void imGrayScale::thread_tmp_i_i_cast_fu_319_p1() {
    tmp_i_i_cast_fu_319_p1 = esl_sext<12,11>(tmp_i_i_16_fu_314_p2.read());
}

void imGrayScale::thread_tmp_i_i_fu_293_p1() {
    tmp_i_i_fu_293_p1 = esl_zext<112,53>(p_Result_s_fu_286_p3.read());
}

void imGrayScale::thread_tmp_i_i_i_cast3_fu_297_p1() {
    tmp_i_i_i_cast3_fu_297_p1 = esl_zext<12,11>(loc_V_reg_495.read());
}

void imGrayScale::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_fu_192_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if (esl_seteq<1,1,1>(tmp_18_fu_207_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state15;
            break;
        case 16384 : 
            ap_NS_fsm = ap_ST_fsm_state16;
            break;
        case 32768 : 
            ap_NS_fsm = ap_ST_fsm_state17;
            break;
        case 65536 : 
            ap_NS_fsm = ap_ST_fsm_state18;
            break;
        case 131072 : 
            ap_NS_fsm = ap_ST_fsm_state19;
            break;
        case 262144 : 
            ap_NS_fsm = ap_ST_fsm_state20;
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state21;
            break;
        case 1048576 : 
            ap_NS_fsm = ap_ST_fsm_state22;
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state23;
            break;
        case 4194304 : 
            ap_NS_fsm = ap_ST_fsm_state24;
            break;
        case 8388608 : 
            ap_NS_fsm = ap_ST_fsm_state25;
            break;
        case 16777216 : 
            ap_NS_fsm = ap_ST_fsm_state26;
            break;
        case 33554432 : 
            ap_NS_fsm = ap_ST_fsm_state27;
            break;
        case 67108864 : 
            ap_NS_fsm = ap_ST_fsm_state28;
            break;
        case 134217728 : 
            ap_NS_fsm = ap_ST_fsm_state29;
            break;
        case 268435456 : 
            ap_NS_fsm = ap_ST_fsm_state30;
            break;
        case 536870912 : 
            ap_NS_fsm = ap_ST_fsm_state31;
            break;
        case 1073741824 : 
            ap_NS_fsm = ap_ST_fsm_state3;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<31>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

}

