// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "imTemplateMatching.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic imTemplateMatching::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic imTemplateMatching::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state1 = "1";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state2 = "10";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state3 = "100";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state4 = "1000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state5 = "10000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state6 = "100000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state7 = "1000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state8 = "10000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state9 = "100000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state10 = "1000000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state11 = "10000000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state12 = "100000000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<14> imTemplateMatching::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<32> imTemplateMatching::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<1> imTemplateMatching::ap_const_lv1_1 = "1";
const sc_lv<32> imTemplateMatching::ap_const_lv32_2 = "10";
const sc_lv<32> imTemplateMatching::ap_const_lv32_7 = "111";
const sc_lv<32> imTemplateMatching::ap_const_lv32_8 = "1000";
const sc_lv<1> imTemplateMatching::ap_const_lv1_0 = "0";
const sc_lv<32> imTemplateMatching::ap_const_lv32_9 = "1001";
const sc_lv<32> imTemplateMatching::ap_const_lv32_C = "1100";
const sc_lv<31> imTemplateMatching::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<42> imTemplateMatching::ap_const_lv42_0 = "000000000000000000000000000000000000000000";
const sc_lv<32> imTemplateMatching::ap_const_lv32_D = "1101";
const sc_lv<32> imTemplateMatching::ap_const_lv32_4 = "100";
const sc_lv<32> imTemplateMatching::ap_const_lv32_3 = "11";
const sc_lv<32> imTemplateMatching::ap_const_lv32_5 = "101";
const sc_lv<32> imTemplateMatching::ap_const_lv32_1 = "1";
const sc_lv<32> imTemplateMatching::ap_const_lv32_6 = "110";
const sc_lv<32> imTemplateMatching::ap_const_lv32_A = "1010";
const sc_lv<32> imTemplateMatching::ap_const_lv32_B = "1011";
const sc_lv<42> imTemplateMatching::ap_const_lv42_4B0 = "10010110000";
const sc_lv<31> imTemplateMatching::ap_const_lv31_1 = "1";
const sc_lv<22> imTemplateMatching::ap_const_lv22_4B0 = "10010110000";

imTemplateMatching::imTemplateMatching(sc_module_name name) : sc_module(name), mVcdFile(0) {
    grp_imGreyNormalization_fu_144 = new imGreyNormalization("grp_imGreyNormalization_fu_144");
    grp_imGreyNormalization_fu_144->ap_clk(ap_clk);
    grp_imGreyNormalization_fu_144->ap_rst(ap_rst);
    grp_imGreyNormalization_fu_144->ap_start(grp_imGreyNormalization_fu_144_ap_start);
    grp_imGreyNormalization_fu_144->ap_done(grp_imGreyNormalization_fu_144_ap_done);
    grp_imGreyNormalization_fu_144->ap_idle(grp_imGreyNormalization_fu_144_ap_idle);
    grp_imGreyNormalization_fu_144->ap_ready(grp_imGreyNormalization_fu_144_ap_ready);
    grp_imGreyNormalization_fu_144->imINPUT_address0(grp_imGreyNormalization_fu_144_imINPUT_address0);
    grp_imGreyNormalization_fu_144->imINPUT_ce0(grp_imGreyNormalization_fu_144_imINPUT_ce0);
    grp_imGreyNormalization_fu_144->imINPUT_we0(grp_imGreyNormalization_fu_144_imINPUT_we0);
    grp_imGreyNormalization_fu_144->imINPUT_d0(grp_imGreyNormalization_fu_144_imINPUT_d0);
    grp_imGreyNormalization_fu_144->imINPUT_q0(grp_imGreyNormalization_fu_144_imINPUT_q0);
    grp_imGreyNormalization_fu_144->imHeight(grp_imGreyNormalization_fu_144_imHeight);
    grp_imGreyNormalization_fu_144->imWidth(imWidth);
    grp_imGrayScale_fu_153 = new imGrayScale("grp_imGrayScale_fu_153");
    grp_imGrayScale_fu_153->ap_clk(ap_clk);
    grp_imGrayScale_fu_153->ap_rst(ap_rst);
    grp_imGrayScale_fu_153->ap_start(grp_imGrayScale_fu_153_ap_start);
    grp_imGrayScale_fu_153->ap_done(grp_imGrayScale_fu_153_ap_done);
    grp_imGrayScale_fu_153->ap_idle(grp_imGrayScale_fu_153_ap_idle);
    grp_imGrayScale_fu_153->ap_ready(grp_imGrayScale_fu_153_ap_ready);
    grp_imGrayScale_fu_153->imINPUT_address0(grp_imGrayScale_fu_153_imINPUT_address0);
    grp_imGrayScale_fu_153->imINPUT_ce0(grp_imGrayScale_fu_153_imINPUT_ce0);
    grp_imGrayScale_fu_153->imINPUT_q0(grp_imGrayScale_fu_153_imINPUT_q0);
    grp_imGrayScale_fu_153->imOUTPUT_address0(grp_imGrayScale_fu_153_imOUTPUT_address0);
    grp_imGrayScale_fu_153->imOUTPUT_ce0(grp_imGrayScale_fu_153_imOUTPUT_ce0);
    grp_imGrayScale_fu_153->imOUTPUT_we0(grp_imGrayScale_fu_153_imOUTPUT_we0);
    grp_imGrayScale_fu_153->imOUTPUT_d0(grp_imGrayScale_fu_153_imOUTPUT_d0);
    grp_imGrayScale_fu_153->imHeight(grp_imGrayScale_fu_153_imHeight);
    grp_imGrayScale_fu_153->imWidth(grp_imGrayScale_fu_153_imWidth);
    grp_imDiff_fu_169 = new imDiff("grp_imDiff_fu_169");
    grp_imDiff_fu_169->ap_clk(ap_clk);
    grp_imDiff_fu_169->ap_rst(ap_rst);
    grp_imDiff_fu_169->ap_start(grp_imDiff_fu_169_ap_start);
    grp_imDiff_fu_169->ap_done(grp_imDiff_fu_169_ap_done);
    grp_imDiff_fu_169->ap_idle(grp_imDiff_fu_169_ap_idle);
    grp_imDiff_fu_169->ap_ready(grp_imDiff_fu_169_ap_ready);
    grp_imDiff_fu_169->imINPUT_address0(grp_imDiff_fu_169_imINPUT_address0);
    grp_imDiff_fu_169->imINPUT_ce0(grp_imDiff_fu_169_imINPUT_ce0);
    grp_imDiff_fu_169->imINPUT_q0(imOUTPUT_q0);
    grp_imDiff_fu_169->imHeight(imHeight);
    grp_imDiff_fu_169->imWidth(imWidth);
    grp_imDiff_fu_169->tplINPUT_address0(grp_imDiff_fu_169_tplINPUT_address0);
    grp_imDiff_fu_169->tplINPUT_ce0(grp_imDiff_fu_169_tplINPUT_ce0);
    grp_imDiff_fu_169->tplINPUT_q0(tplOUTPUT_q0);
    grp_imDiff_fu_169->tplHeight(tplHeight);
    grp_imDiff_fu_169->tplWidth(tplWidth);
    grp_imDiff_fu_169->ap_return_0(grp_imDiff_fu_169_ap_return_0);
    grp_imDiff_fu_169->ap_return_1(grp_imDiff_fu_169_ap_return_1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_i_fu_203_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_i_fu_203_p2 );

    SC_METHOD(thread_col_fu_242_p2);
    sensitive << ( col_i_reg_133 );

    SC_METHOD(thread_col_i_cast_fu_233_p1);
    sensitive << ( col_i_reg_133 );

    SC_METHOD(thread_grp_imDiff_fu_169_ap_start);
    sensitive << ( ap_reg_grp_imDiff_fu_169_ap_start );

    SC_METHOD(thread_grp_imGrayScale_fu_153_ap_start);
    sensitive << ( ap_reg_grp_imGrayScale_fu_153_ap_start );

    SC_METHOD(thread_grp_imGrayScale_fu_153_imHeight);
    sensitive << ( imHeight );
    sensitive << ( tplHeight );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_imGrayScale_fu_153_imINPUT_q0);
    sensitive << ( imINPUT_q0 );
    sensitive << ( tplINPUT_q0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_imGrayScale_fu_153_imWidth);
    sensitive << ( imWidth );
    sensitive << ( tplWidth );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_grp_imGreyNormalization_fu_144_ap_start);
    sensitive << ( ap_reg_grp_imGreyNormalization_fu_144_ap_start );

    SC_METHOD(thread_grp_imGreyNormalization_fu_144_imHeight);
    sensitive << ( imHeight );
    sensitive << ( tplWidth );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_grp_imGreyNormalization_fu_144_imINPUT_q0);
    sensitive << ( imOUTPUT_q0 );
    sensitive << ( tplOUTPUT_q0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_imINPUT_address0);
    sensitive << ( grp_imGrayScale_fu_153_imINPUT_address0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_imINPUT_ce0);
    sensitive << ( grp_imGrayScale_fu_153_imINPUT_ce0 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_imOUTPUT_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_address0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_address0 );
    sensitive << ( grp_imDiff_fu_169_imINPUT_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( tmp_3_cast_fu_280_p1 );

    SC_METHOD(thread_imOUTPUT_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_ce0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_ce0 );
    sensitive << ( grp_imDiff_fu_169_imINPUT_ce0 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_imOUTPUT_d0);
    sensitive << ( tplINPUT_q0 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_d0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_d0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_imOUTPUT_we0);
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_we0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_we0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state2 );

    SC_METHOD(thread_next_mul_fu_193_p2);
    sensitive << ( phi_mul_reg_122 );

    SC_METHOD(thread_row_fu_208_p2);
    sensitive << ( row_i_reg_111 );

    SC_METHOD(thread_row_i_cast_fu_199_p1);
    sensitive << ( row_i_reg_111 );

    SC_METHOD(thread_tmp_10_fu_269_p2);
    sensitive << ( tmp_9_fu_266_p1 );
    sensitive << ( tmp_8_fu_262_p1 );

    SC_METHOD(thread_tmp_1_fu_227_p2);
    sensitive << ( tmp_6_fu_221_p2 );

    SC_METHOD(thread_tmp_2_cast_fu_257_p1);
    sensitive << ( tmp_2_fu_252_p2 );

    SC_METHOD(thread_tmp_2_fu_252_p2);
    sensitive << ( tmp_reg_323 );
    sensitive << ( tmp_7_fu_248_p1 );

    SC_METHOD(thread_tmp_3_cast_fu_280_p1);
    sensitive << ( tmp_3_reg_359 );

    SC_METHOD(thread_tmp_3_fu_275_p2);
    sensitive << ( tmp_1_reg_341 );
    sensitive << ( tmp_10_fu_269_p2 );

    SC_METHOD(thread_tmp_4_fu_214_p1);
    sensitive << ( row_i_reg_111 );

    SC_METHOD(thread_tmp_56_i_fu_237_p2);
    sensitive << ( tplWidth );
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( col_i_cast_fu_233_p1 );

    SC_METHOD(thread_tmp_5_fu_218_p1);
    sensitive << ( template_match_posit_1_reg_318 );

    SC_METHOD(thread_tmp_6_fu_221_p2);
    sensitive << ( tmp_5_fu_218_p1 );
    sensitive << ( tmp_4_fu_214_p1 );

    SC_METHOD(thread_tmp_7_fu_248_p1);
    sensitive << ( col_i_reg_133 );

    SC_METHOD(thread_tmp_8_fu_262_p1);
    sensitive << ( col_i_reg_133 );

    SC_METHOD(thread_tmp_9_fu_266_p1);
    sensitive << ( template_match_posit_reg_313 );

    SC_METHOD(thread_tmp_fu_189_p1);
    sensitive << ( phi_mul_reg_122 );

    SC_METHOD(thread_tmp_i_fu_203_p2);
    sensitive << ( tplHeight );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( row_i_cast_fu_199_p1 );

    SC_METHOD(thread_tplINPUT_address0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( grp_imGrayScale_fu_153_imINPUT_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( tmp_2_cast_fu_257_p1 );

    SC_METHOD(thread_tplINPUT_ce0);
    sensitive << ( ap_CS_fsm_state10 );
    sensitive << ( ap_CS_fsm_state13 );
    sensitive << ( grp_imGrayScale_fu_153_imINPUT_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state11 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_tplOUTPUT_address0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_address0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_address0 );
    sensitive << ( grp_imDiff_fu_169_tplINPUT_address0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tplOUTPUT_ce0);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_ce0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_ce0 );
    sensitive << ( grp_imDiff_fu_169_tplINPUT_ce0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tplOUTPUT_d0);
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_d0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_d0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tplOUTPUT_we0);
    sensitive << ( grp_imGreyNormalization_fu_144_imINPUT_we0 );
    sensitive << ( grp_imGrayScale_fu_153_imOUTPUT_we0 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( grp_imDiff_fu_169_ap_done );
    sensitive << ( tmp_i_fu_203_p2 );
    sensitive << ( tmp_56_i_fu_237_p2 );
    sensitive << ( grp_imGreyNormalization_fu_144_ap_done );
    sensitive << ( grp_imGrayScale_fu_153_ap_done );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "00000000000001";
    ap_reg_grp_imGreyNormalization_fu_144_ap_start = SC_LOGIC_0;
    ap_reg_grp_imGrayScale_fu_153_ap_start = SC_LOGIC_0;
    ap_reg_grp_imDiff_fu_169_ap_start = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "imTemplateMatching_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, imINPUT_address0, "(port)imINPUT_address0");
    sc_trace(mVcdFile, imINPUT_ce0, "(port)imINPUT_ce0");
    sc_trace(mVcdFile, imINPUT_q0, "(port)imINPUT_q0");
    sc_trace(mVcdFile, imOUTPUT_address0, "(port)imOUTPUT_address0");
    sc_trace(mVcdFile, imOUTPUT_ce0, "(port)imOUTPUT_ce0");
    sc_trace(mVcdFile, imOUTPUT_we0, "(port)imOUTPUT_we0");
    sc_trace(mVcdFile, imOUTPUT_d0, "(port)imOUTPUT_d0");
    sc_trace(mVcdFile, imOUTPUT_q0, "(port)imOUTPUT_q0");
    sc_trace(mVcdFile, imHeight, "(port)imHeight");
    sc_trace(mVcdFile, imWidth, "(port)imWidth");
    sc_trace(mVcdFile, tplINPUT_address0, "(port)tplINPUT_address0");
    sc_trace(mVcdFile, tplINPUT_ce0, "(port)tplINPUT_ce0");
    sc_trace(mVcdFile, tplINPUT_q0, "(port)tplINPUT_q0");
    sc_trace(mVcdFile, tplOUTPUT_address0, "(port)tplOUTPUT_address0");
    sc_trace(mVcdFile, tplOUTPUT_ce0, "(port)tplOUTPUT_ce0");
    sc_trace(mVcdFile, tplOUTPUT_we0, "(port)tplOUTPUT_we0");
    sc_trace(mVcdFile, tplOUTPUT_d0, "(port)tplOUTPUT_d0");
    sc_trace(mVcdFile, tplOUTPUT_q0, "(port)tplOUTPUT_q0");
    sc_trace(mVcdFile, tplHeight, "(port)tplHeight");
    sc_trace(mVcdFile, tplWidth, "(port)tplWidth");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, template_match_posit_reg_313, "template_match_posit_reg_313");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, grp_imDiff_fu_169_ap_done, "grp_imDiff_fu_169_ap_done");
    sc_trace(mVcdFile, template_match_posit_1_reg_318, "template_match_posit_1_reg_318");
    sc_trace(mVcdFile, tmp_fu_189_p1, "tmp_fu_189_p1");
    sc_trace(mVcdFile, tmp_reg_323, "tmp_reg_323");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, next_mul_fu_193_p2, "next_mul_fu_193_p2");
    sc_trace(mVcdFile, next_mul_reg_328, "next_mul_reg_328");
    sc_trace(mVcdFile, row_fu_208_p2, "row_fu_208_p2");
    sc_trace(mVcdFile, row_reg_336, "row_reg_336");
    sc_trace(mVcdFile, tmp_1_fu_227_p2, "tmp_1_fu_227_p2");
    sc_trace(mVcdFile, tmp_1_reg_341, "tmp_1_reg_341");
    sc_trace(mVcdFile, tmp_i_fu_203_p2, "tmp_i_fu_203_p2");
    sc_trace(mVcdFile, col_fu_242_p2, "col_fu_242_p2");
    sc_trace(mVcdFile, col_reg_349, "col_reg_349");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_56_i_fu_237_p2, "tmp_56_i_fu_237_p2");
    sc_trace(mVcdFile, tmp_3_fu_275_p2, "tmp_3_fu_275_p2");
    sc_trace(mVcdFile, tmp_3_reg_359, "tmp_3_reg_359");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_ap_start, "grp_imGreyNormalization_fu_144_ap_start");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_ap_done, "grp_imGreyNormalization_fu_144_ap_done");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_ap_idle, "grp_imGreyNormalization_fu_144_ap_idle");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_ap_ready, "grp_imGreyNormalization_fu_144_ap_ready");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_imINPUT_address0, "grp_imGreyNormalization_fu_144_imINPUT_address0");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_imINPUT_ce0, "grp_imGreyNormalization_fu_144_imINPUT_ce0");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_imINPUT_we0, "grp_imGreyNormalization_fu_144_imINPUT_we0");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_imINPUT_d0, "grp_imGreyNormalization_fu_144_imINPUT_d0");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_imINPUT_q0, "grp_imGreyNormalization_fu_144_imINPUT_q0");
    sc_trace(mVcdFile, grp_imGreyNormalization_fu_144_imHeight, "grp_imGreyNormalization_fu_144_imHeight");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_ap_start, "grp_imGrayScale_fu_153_ap_start");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_ap_done, "grp_imGrayScale_fu_153_ap_done");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_ap_idle, "grp_imGrayScale_fu_153_ap_idle");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_ap_ready, "grp_imGrayScale_fu_153_ap_ready");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imINPUT_address0, "grp_imGrayScale_fu_153_imINPUT_address0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imINPUT_ce0, "grp_imGrayScale_fu_153_imINPUT_ce0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imINPUT_q0, "grp_imGrayScale_fu_153_imINPUT_q0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imOUTPUT_address0, "grp_imGrayScale_fu_153_imOUTPUT_address0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imOUTPUT_ce0, "grp_imGrayScale_fu_153_imOUTPUT_ce0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imOUTPUT_we0, "grp_imGrayScale_fu_153_imOUTPUT_we0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imOUTPUT_d0, "grp_imGrayScale_fu_153_imOUTPUT_d0");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imHeight, "grp_imGrayScale_fu_153_imHeight");
    sc_trace(mVcdFile, grp_imGrayScale_fu_153_imWidth, "grp_imGrayScale_fu_153_imWidth");
    sc_trace(mVcdFile, grp_imDiff_fu_169_ap_start, "grp_imDiff_fu_169_ap_start");
    sc_trace(mVcdFile, grp_imDiff_fu_169_ap_idle, "grp_imDiff_fu_169_ap_idle");
    sc_trace(mVcdFile, grp_imDiff_fu_169_ap_ready, "grp_imDiff_fu_169_ap_ready");
    sc_trace(mVcdFile, grp_imDiff_fu_169_imINPUT_address0, "grp_imDiff_fu_169_imINPUT_address0");
    sc_trace(mVcdFile, grp_imDiff_fu_169_imINPUT_ce0, "grp_imDiff_fu_169_imINPUT_ce0");
    sc_trace(mVcdFile, grp_imDiff_fu_169_tplINPUT_address0, "grp_imDiff_fu_169_tplINPUT_address0");
    sc_trace(mVcdFile, grp_imDiff_fu_169_tplINPUT_ce0, "grp_imDiff_fu_169_tplINPUT_ce0");
    sc_trace(mVcdFile, grp_imDiff_fu_169_ap_return_0, "grp_imDiff_fu_169_ap_return_0");
    sc_trace(mVcdFile, grp_imDiff_fu_169_ap_return_1, "grp_imDiff_fu_169_ap_return_1");
    sc_trace(mVcdFile, row_i_reg_111, "row_i_reg_111");
    sc_trace(mVcdFile, phi_mul_reg_122, "phi_mul_reg_122");
    sc_trace(mVcdFile, col_i_reg_133, "col_i_reg_133");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, ap_reg_grp_imGreyNormalization_fu_144_ap_start, "ap_reg_grp_imGreyNormalization_fu_144_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, ap_reg_grp_imGrayScale_fu_153_ap_start, "ap_reg_grp_imGrayScale_fu_153_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, ap_reg_grp_imDiff_fu_169_ap_start, "ap_reg_grp_imDiff_fu_169_ap_start");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, tmp_2_cast_fu_257_p1, "tmp_2_cast_fu_257_p1");
    sc_trace(mVcdFile, tmp_3_cast_fu_280_p1, "tmp_3_cast_fu_280_p1");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, row_i_cast_fu_199_p1, "row_i_cast_fu_199_p1");
    sc_trace(mVcdFile, tmp_5_fu_218_p1, "tmp_5_fu_218_p1");
    sc_trace(mVcdFile, tmp_4_fu_214_p1, "tmp_4_fu_214_p1");
    sc_trace(mVcdFile, tmp_6_fu_221_p2, "tmp_6_fu_221_p2");
    sc_trace(mVcdFile, col_i_cast_fu_233_p1, "col_i_cast_fu_233_p1");
    sc_trace(mVcdFile, tmp_7_fu_248_p1, "tmp_7_fu_248_p1");
    sc_trace(mVcdFile, tmp_2_fu_252_p2, "tmp_2_fu_252_p2");
    sc_trace(mVcdFile, tmp_9_fu_266_p1, "tmp_9_fu_266_p1");
    sc_trace(mVcdFile, tmp_8_fu_262_p1, "tmp_8_fu_262_p1");
    sc_trace(mVcdFile, tmp_10_fu_269_p2, "tmp_10_fu_269_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("imTemplateMatching.hdltvin.dat");
    mHdltvoutHandle.open("imTemplateMatching.hdltvout.dat");
}

imTemplateMatching::~imTemplateMatching() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete grp_imGreyNormalization_fu_144;
    delete grp_imGrayScale_fu_153;
    delete grp_imDiff_fu_169;
}

void imTemplateMatching::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_imDiff_fu_169_ap_start = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state7.read()))) {
            ap_reg_grp_imDiff_fu_169_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_imDiff_fu_169_ap_ready.read())) {
            ap_reg_grp_imDiff_fu_169_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_imGrayScale_fu_153_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1) && 
              !esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) || 
             (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())))) {
            ap_reg_grp_imGrayScale_fu_153_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_imGrayScale_fu_153_ap_ready.read())) {
            ap_reg_grp_imGrayScale_fu_153_ap_start = ap_const_logic_0;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_grp_imGreyNormalization_fu_144_ap_start = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state3.read())) || 
             (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state5.read())))) {
            ap_reg_grp_imGreyNormalization_fu_144_ap_start = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_imGreyNormalization_fu_144_ap_ready.read())) {
            ap_reg_grp_imGreyNormalization_fu_144_ap_start = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read()))) {
        col_i_reg_133 = col_reg_349.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
                !esl_seteq<1,1,1>(tmp_i_fu_203_p2.read(), ap_const_lv1_0))) {
        col_i_reg_133 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_56_i_fu_237_p2.read()))) {
        phi_mul_reg_122 = next_mul_reg_328.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_imDiff_fu_169_ap_done.read()))) {
        phi_mul_reg_122 = ap_const_lv42_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, tmp_56_i_fu_237_p2.read()))) {
        row_i_reg_111 = row_reg_336.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && 
                !esl_seteq<1,1,1>(ap_const_logic_0, grp_imDiff_fu_169_ap_done.read()))) {
        row_i_reg_111 = ap_const_lv31_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()))) {
        col_reg_349 = col_fu_242_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()))) {
        next_mul_reg_328 = next_mul_fu_193_p2.read();
        row_reg_336 = row_fu_208_p2.read();
        tmp_reg_323 = tmp_fu_189_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()) && !esl_seteq<1,1,1>(ap_const_logic_0, grp_imDiff_fu_169_ap_done.read()))) {
        template_match_posit_1_reg_318 = grp_imDiff_fu_169_ap_return_1.read();
        template_match_posit_reg_313 = grp_imDiff_fu_169_ap_return_0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && !esl_seteq<1,1,1>(tmp_i_fu_203_p2.read(), ap_const_lv1_0))) {
        tmp_1_reg_341 = tmp_1_fu_227_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()) && !esl_seteq<1,1,1>(ap_const_lv1_0, tmp_56_i_fu_237_p2.read()))) {
        tmp_3_reg_359 = tmp_3_fu_275_p2.read();
    }
}

void imTemplateMatching::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read().range(0, 0);
}

void imTemplateMatching::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read().range(9, 9);
}

void imTemplateMatching::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read().range(10, 10);
}

void imTemplateMatching::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read().range(11, 11);
}

void imTemplateMatching::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read().range(12, 12);
}

void imTemplateMatching::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read().range(13, 13);
}

void imTemplateMatching::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read().range(1, 1);
}

void imTemplateMatching::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read().range(2, 2);
}

void imTemplateMatching::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read().range(3, 3);
}

void imTemplateMatching::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read().range(4, 4);
}

void imTemplateMatching::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read().range(5, 5);
}

void imTemplateMatching::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read().range(6, 6);
}

void imTemplateMatching::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read().range(7, 7);
}

void imTemplateMatching::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read().range(8, 8);
}

void imTemplateMatching::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_203_p2.read(), ap_const_lv1_0))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_CS_fsm_state1.read(), ap_const_lv1_1))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(tmp_i_fu_203_p2.read(), ap_const_lv1_0))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_col_fu_242_p2() {
    col_fu_242_p2 = (!col_i_reg_133.read().is_01() || !ap_const_lv31_1.is_01())? sc_lv<31>(): (sc_biguint<31>(col_i_reg_133.read()) + sc_biguint<31>(ap_const_lv31_1));
}

void imTemplateMatching::thread_col_i_cast_fu_233_p1() {
    col_i_cast_fu_233_p1 = esl_zext<32,31>(col_i_reg_133.read());
}

void imTemplateMatching::thread_grp_imDiff_fu_169_ap_start() {
    grp_imDiff_fu_169_ap_start = ap_reg_grp_imDiff_fu_169_ap_start.read();
}

void imTemplateMatching::thread_grp_imGrayScale_fu_153_ap_start() {
    grp_imGrayScale_fu_153_ap_start = ap_reg_grp_imGrayScale_fu_153_ap_start.read();
}

void imTemplateMatching::thread_grp_imGrayScale_fu_153_imHeight() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        grp_imGrayScale_fu_153_imHeight = tplHeight.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        grp_imGrayScale_fu_153_imHeight = imHeight.read();
    } else {
        grp_imGrayScale_fu_153_imHeight = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_grp_imGrayScale_fu_153_imINPUT_q0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        grp_imGrayScale_fu_153_imINPUT_q0 = tplINPUT_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        grp_imGrayScale_fu_153_imINPUT_q0 = imINPUT_q0.read();
    } else {
        grp_imGrayScale_fu_153_imINPUT_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_grp_imGrayScale_fu_153_imWidth() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        grp_imGrayScale_fu_153_imWidth = tplWidth.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        grp_imGrayScale_fu_153_imWidth = imWidth.read();
    } else {
        grp_imGrayScale_fu_153_imWidth = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_grp_imGreyNormalization_fu_144_ap_start() {
    grp_imGreyNormalization_fu_144_ap_start = ap_reg_grp_imGreyNormalization_fu_144_ap_start.read();
}

void imTemplateMatching::thread_grp_imGreyNormalization_fu_144_imHeight() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        grp_imGreyNormalization_fu_144_imHeight = tplWidth.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        grp_imGreyNormalization_fu_144_imHeight = imHeight.read();
    } else {
        grp_imGreyNormalization_fu_144_imHeight = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_grp_imGreyNormalization_fu_144_imINPUT_q0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        grp_imGreyNormalization_fu_144_imINPUT_q0 = tplOUTPUT_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        grp_imGreyNormalization_fu_144_imINPUT_q0 = imOUTPUT_q0.read();
    } else {
        grp_imGreyNormalization_fu_144_imINPUT_q0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_imINPUT_address0() {
    imINPUT_address0 = grp_imGrayScale_fu_153_imINPUT_address0.read();
}

void imTemplateMatching::thread_imINPUT_ce0() {
    imINPUT_ce0 = grp_imGrayScale_fu_153_imINPUT_ce0.read();
}

void imTemplateMatching::thread_imOUTPUT_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        imOUTPUT_address0 =  (sc_lv<21>) (tmp_3_cast_fu_280_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        imOUTPUT_address0 = grp_imDiff_fu_169_imINPUT_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        imOUTPUT_address0 = grp_imGrayScale_fu_153_imOUTPUT_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        imOUTPUT_address0 = grp_imGreyNormalization_fu_144_imINPUT_address0.read();
    } else {
        imOUTPUT_address0 =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
    }
}

void imTemplateMatching::thread_imOUTPUT_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state14.read())))) {
        imOUTPUT_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        imOUTPUT_ce0 = grp_imDiff_fu_169_imINPUT_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        imOUTPUT_ce0 = grp_imGrayScale_fu_153_imOUTPUT_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        imOUTPUT_ce0 = grp_imGreyNormalization_fu_144_imINPUT_ce0.read();
    } else {
        imOUTPUT_ce0 = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_imOUTPUT_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read()))) {
        imOUTPUT_d0 = tplINPUT_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        imOUTPUT_d0 = grp_imGrayScale_fu_153_imOUTPUT_d0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        imOUTPUT_d0 = grp_imGreyNormalization_fu_144_imINPUT_d0.read();
    } else {
        imOUTPUT_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_imOUTPUT_we0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())))) {
        imOUTPUT_we0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state2.read()))) {
        imOUTPUT_we0 = grp_imGrayScale_fu_153_imOUTPUT_we0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        imOUTPUT_we0 = grp_imGreyNormalization_fu_144_imINPUT_we0.read();
    } else {
        imOUTPUT_we0 = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_next_mul_fu_193_p2() {
    next_mul_fu_193_p2 = (!ap_const_lv42_4B0.is_01() || !phi_mul_reg_122.read().is_01())? sc_lv<42>(): (sc_biguint<42>(ap_const_lv42_4B0) + sc_biguint<42>(phi_mul_reg_122.read()));
}

void imTemplateMatching::thread_row_fu_208_p2() {
    row_fu_208_p2 = (!ap_const_lv31_1.is_01() || !row_i_reg_111.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_1) + sc_biguint<31>(row_i_reg_111.read()));
}

void imTemplateMatching::thread_row_i_cast_fu_199_p1() {
    row_i_cast_fu_199_p1 = esl_zext<32,31>(row_i_reg_111.read());
}

void imTemplateMatching::thread_tmp_10_fu_269_p2() {
    tmp_10_fu_269_p2 = (!tmp_9_fu_266_p1.read().is_01() || !tmp_8_fu_262_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_9_fu_266_p1.read()) + sc_biguint<22>(tmp_8_fu_262_p1.read()));
}

void imTemplateMatching::thread_tmp_1_fu_227_p2() {
    tmp_1_fu_227_p2 = (!ap_const_lv22_4B0.is_01() || !tmp_6_fu_221_p2.read().is_01())? sc_lv<22>(): sc_biguint<22>(ap_const_lv22_4B0) * sc_bigint<22>(tmp_6_fu_221_p2.read());
}

void imTemplateMatching::thread_tmp_2_cast_fu_257_p1() {
    tmp_2_cast_fu_257_p1 = esl_zext<64,22>(tmp_2_fu_252_p2.read());
}

void imTemplateMatching::thread_tmp_2_fu_252_p2() {
    tmp_2_fu_252_p2 = (!tmp_reg_323.read().is_01() || !tmp_7_fu_248_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_reg_323.read()) + sc_biguint<22>(tmp_7_fu_248_p1.read()));
}

void imTemplateMatching::thread_tmp_3_cast_fu_280_p1() {
    tmp_3_cast_fu_280_p1 = esl_sext<64,22>(tmp_3_reg_359.read());
}

void imTemplateMatching::thread_tmp_3_fu_275_p2() {
    tmp_3_fu_275_p2 = (!tmp_1_reg_341.read().is_01() || !tmp_10_fu_269_p2.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_1_reg_341.read()) + sc_biguint<22>(tmp_10_fu_269_p2.read()));
}

void imTemplateMatching::thread_tmp_4_fu_214_p1() {
    tmp_4_fu_214_p1 = row_i_reg_111.read().range(22-1, 0);
}

void imTemplateMatching::thread_tmp_56_i_fu_237_p2() {
    tmp_56_i_fu_237_p2 = (!col_i_cast_fu_233_p1.read().is_01() || !tplWidth.read().is_01())? sc_lv<1>(): (sc_bigint<32>(col_i_cast_fu_233_p1.read()) < sc_bigint<32>(tplWidth.read()));
}

void imTemplateMatching::thread_tmp_5_fu_218_p1() {
    tmp_5_fu_218_p1 = template_match_posit_1_reg_318.read().range(22-1, 0);
}

void imTemplateMatching::thread_tmp_6_fu_221_p2() {
    tmp_6_fu_221_p2 = (!tmp_5_fu_218_p1.read().is_01() || !tmp_4_fu_214_p1.read().is_01())? sc_lv<22>(): (sc_biguint<22>(tmp_5_fu_218_p1.read()) + sc_biguint<22>(tmp_4_fu_214_p1.read()));
}

void imTemplateMatching::thread_tmp_7_fu_248_p1() {
    tmp_7_fu_248_p1 = col_i_reg_133.read().range(22-1, 0);
}

void imTemplateMatching::thread_tmp_8_fu_262_p1() {
    tmp_8_fu_262_p1 = col_i_reg_133.read().range(22-1, 0);
}

void imTemplateMatching::thread_tmp_9_fu_266_p1() {
    tmp_9_fu_266_p1 = template_match_posit_reg_313.read().range(22-1, 0);
}

void imTemplateMatching::thread_tmp_fu_189_p1() {
    tmp_fu_189_p1 = phi_mul_reg_122.read().range(22-1, 0);
}

void imTemplateMatching::thread_tmp_i_fu_203_p2() {
    tmp_i_fu_203_p2 = (!row_i_cast_fu_199_p1.read().is_01() || !tplHeight.read().is_01())? sc_lv<1>(): (sc_bigint<32>(row_i_cast_fu_199_p1.read()) < sc_bigint<32>(tplHeight.read()));
}

void imTemplateMatching::thread_tplINPUT_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read()))) {
        tplINPUT_address0 =  (sc_lv<21>) (tmp_2_cast_fu_257_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        tplINPUT_address0 = grp_imGrayScale_fu_153_imINPUT_address0.read();
    } else {
        tplINPUT_address0 =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
    }
}

void imTemplateMatching::thread_tplINPUT_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state10.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state13.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state11.read())) || 
         (esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state12.read())))) {
        tplINPUT_ce0 = ap_const_logic_1;
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        tplINPUT_ce0 = grp_imGrayScale_fu_153_imINPUT_ce0.read();
    } else {
        tplINPUT_ce0 = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_tplOUTPUT_address0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        tplOUTPUT_address0 = grp_imDiff_fu_169_tplINPUT_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        tplOUTPUT_address0 = grp_imGrayScale_fu_153_imOUTPUT_address0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        tplOUTPUT_address0 = grp_imGreyNormalization_fu_144_imINPUT_address0.read();
    } else {
        tplOUTPUT_address0 =  (sc_lv<21>) ("XXXXXXXXXXXXXXXXXXXXX");
    }
}

void imTemplateMatching::thread_tplOUTPUT_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state8.read()))) {
        tplOUTPUT_ce0 = grp_imDiff_fu_169_tplINPUT_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        tplOUTPUT_ce0 = grp_imGrayScale_fu_153_imOUTPUT_ce0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        tplOUTPUT_ce0 = grp_imGreyNormalization_fu_144_imINPUT_ce0.read();
    } else {
        tplOUTPUT_ce0 = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_tplOUTPUT_d0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        tplOUTPUT_d0 = grp_imGrayScale_fu_153_imOUTPUT_d0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        tplOUTPUT_d0 = grp_imGreyNormalization_fu_144_imINPUT_d0.read();
    } else {
        tplOUTPUT_d0 = "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    }
}

void imTemplateMatching::thread_tplOUTPUT_we0() {
    if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state4.read()))) {
        tplOUTPUT_we0 = grp_imGrayScale_fu_153_imOUTPUT_we0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_lv1_1, ap_CS_fsm_state6.read()))) {
        tplOUTPUT_we0 = grp_imGreyNormalization_fu_144_imINPUT_we0.read();
    } else {
        tplOUTPUT_we0 = ap_const_logic_0;
    }
}

void imTemplateMatching::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if (!esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_0)) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_imGrayScale_fu_153_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state2;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            if (!(esl_seteq<1,1,1>(ap_const_logic_0, grp_imGrayScale_fu_153_ap_done.read()) || esl_seteq<1,1,1>(ap_const_logic_0, grp_imGreyNormalization_fu_144_ap_done.read()))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_imGreyNormalization_fu_144_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state7;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if (!esl_seteq<1,1,1>(ap_const_logic_0, grp_imDiff_fu_169_ap_done.read())) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 256 : 
            if (esl_seteq<1,1,1>(tmp_i_fu_203_p2.read(), ap_const_lv1_0)) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state10;
            }
            break;
        case 512 : 
            if (esl_seteq<1,1,1>(ap_const_lv1_0, tmp_56_i_fu_237_p2.read())) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_state11;
            }
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<14>) ("XXXXXXXXXXXXXX");
            break;
    }
}

void imTemplateMatching::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imINPUT_address0\" :  \"" << imINPUT_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imINPUT_ce0\" :  \"" << imINPUT_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"imINPUT_q0\" :  \"" << imINPUT_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imOUTPUT_address0\" :  \"" << imOUTPUT_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imOUTPUT_ce0\" :  \"" << imOUTPUT_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imOUTPUT_we0\" :  \"" << imOUTPUT_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"imOUTPUT_d0\" :  \"" << imOUTPUT_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"imOUTPUT_q0\" :  \"" << imOUTPUT_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"imHeight\" :  \"" << imHeight.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"imWidth\" :  \"" << imWidth.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tplINPUT_address0\" :  \"" << tplINPUT_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tplINPUT_ce0\" :  \"" << tplINPUT_ce0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tplINPUT_q0\" :  \"" << tplINPUT_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tplOUTPUT_address0\" :  \"" << tplOUTPUT_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tplOUTPUT_ce0\" :  \"" << tplOUTPUT_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tplOUTPUT_we0\" :  \"" << tplOUTPUT_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"tplOUTPUT_d0\" :  \"" << tplOUTPUT_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tplOUTPUT_q0\" :  \"" << tplOUTPUT_q0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tplHeight\" :  \"" << tplHeight.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"tplWidth\" :  \"" << tplWidth.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

