// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _imGrayScale_HH_
#define _imGrayScale_HH_

#include "systemc.h"
#include "AESL_pkg.h"

#include "imTemplateMatchinbkb.h"
#include "imTemplateMatchincud.h"
#include "imTemplateMatchindEe.h"

namespace ap_rtl {

struct imGrayScale : public sc_module {
    // Port declarations 15
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<21> > imINPUT_address0;
    sc_out< sc_logic > imINPUT_ce0;
    sc_in< sc_lv<32> > imINPUT_q0;
    sc_out< sc_lv<21> > imOUTPUT_address0;
    sc_out< sc_logic > imOUTPUT_ce0;
    sc_out< sc_logic > imOUTPUT_we0;
    sc_out< sc_lv<32> > imOUTPUT_d0;
    sc_in< sc_lv<32> > imHeight;
    sc_in< sc_lv<32> > imWidth;
    sc_signal< sc_logic > ap_var_for_const0;
    sc_signal< sc_lv<64> > ap_var_for_const1;


    // Module declarations
    imGrayScale(sc_module_name name);
    SC_HAS_PROCESS(imGrayScale);

    ~imGrayScale();

    sc_trace_file* mVcdFile;

    imTemplateMatchinbkb<1,5,64,64,64>* imTemplateMatchinbkb_x_U10;
    imTemplateMatchincud<1,6,64,64,64>* imTemplateMatchincud_x_U11;
    imTemplateMatchincud<1,6,64,64,64>* imTemplateMatchincud_x_U12;
    imTemplateMatchindEe<1,6,32,64>* imTemplateMatchindEe_x_U13;
    imTemplateMatchindEe<1,6,32,64>* imTemplateMatchindEe_x_U14;
    sc_signal< sc_lv<31> > ap_CS_fsm;
    sc_signal< sc_lv<1> > ap_CS_fsm_state1;
    sc_signal< sc_lv<64> > grp_fu_161_p2;
    sc_signal< sc_lv<64> > reg_178;
    sc_signal< sc_lv<1> > ap_CS_fsm_state18;
    sc_signal< sc_lv<1> > ap_CS_fsm_state23;
    sc_signal< sc_lv<22> > tmp_40_fu_184_p1;
    sc_signal< sc_lv<22> > tmp_40_reg_410;
    sc_signal< sc_lv<1> > ap_CS_fsm_state2;
    sc_signal< sc_lv<42> > next_mul_fu_188_p2;
    sc_signal< sc_lv<42> > next_mul_reg_415;
    sc_signal< sc_lv<31> > row_4_fu_203_p2;
    sc_signal< sc_lv<31> > row_4_reg_423;
    sc_signal< sc_lv<31> > col_4_fu_218_p2;
    sc_signal< sc_lv<31> > col_4_reg_431;
    sc_signal< sc_lv<1> > ap_CS_fsm_state3;
    sc_signal< sc_lv<64> > tmp_39_cast_fu_233_p1;
    sc_signal< sc_lv<64> > tmp_39_cast_reg_436;
    sc_signal< sc_lv<1> > tmp_18_fu_213_p2;
    sc_signal< sc_lv<8> > tmp_44_fu_238_p1;
    sc_signal< sc_lv<8> > tmp_44_reg_446;
    sc_signal< sc_lv<1> > ap_CS_fsm_state6;
    sc_signal< sc_lv<8> > tmp_23_cast_reg_451;
    sc_signal< sc_lv<8> > tmp_28_cast_reg_456;
    sc_signal< sc_lv<32> > tmp_20_cast_fu_262_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state7;
    sc_signal< sc_lv<64> > grp_fu_172_p1;
    sc_signal< sc_lv<64> > tmp_21_reg_471;
    sc_signal< sc_lv<1> > ap_CS_fsm_state12;
    sc_signal< sc_lv<64> > grp_fu_175_p1;
    sc_signal< sc_lv<64> > tmp_25_reg_476;
    sc_signal< sc_lv<32> > tmp_29_cast_fu_270_p1;
    sc_signal< sc_lv<64> > tmp_30_reg_486;
    sc_signal< sc_lv<1> > ap_CS_fsm_state17;
    sc_signal< sc_lv<64> > grp_fu_166_p2;
    sc_signal< sc_lv<64> > tmp_26_reg_491;
    sc_signal< sc_lv<64> > grp_fu_157_p2;
    sc_signal< sc_lv<64> > tmp_27_reg_496;
    sc_signal< sc_lv<11> > loc_V_reg_501;
    sc_signal< sc_lv<1> > ap_CS_fsm_state28;
    sc_signal< sc_lv<52> > loc_V_3_fu_288_p1;
    sc_signal< sc_lv<52> > loc_V_3_reg_507;
    sc_signal< sc_lv<8> > result_V_fu_383_p3;
    sc_signal< sc_lv<8> > result_V_reg_512;
    sc_signal< sc_lv<1> > ap_CS_fsm_state29;
    sc_signal< sc_lv<1> > ap_CS_fsm_state30;
    sc_signal< sc_lv<31> > row_reg_124;
    sc_signal< sc_lv<42> > phi_mul_reg_135;
    sc_signal< sc_lv<31> > col_reg_146;
    sc_signal< sc_lv<1> > tmp_fu_198_p2;
    sc_signal< sc_lv<1> > ap_CS_fsm_state31;
    sc_signal< sc_lv<1> > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > ap_CS_fsm_state5;
    sc_signal< sc_lv<64> > grp_fu_157_p0;
    sc_signal< sc_lv<64> > grp_fu_157_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state19;
    sc_signal< sc_lv<1> > ap_CS_fsm_state24;
    sc_signal< sc_lv<64> > grp_fu_161_p0;
    sc_signal< sc_lv<64> > grp_fu_161_p1;
    sc_signal< sc_lv<1> > ap_CS_fsm_state13;
    sc_signal< sc_lv<32> > grp_fu_172_p0;
    sc_signal< sc_lv<32> > grp_fu_175_p0;
    sc_signal< sc_lv<32> > row_cast_fu_194_p1;
    sc_signal< sc_lv<32> > col_cast_fu_209_p1;
    sc_signal< sc_lv<22> > tmp_43_fu_224_p1;
    sc_signal< sc_lv<22> > tmp_33_fu_228_p2;
    sc_signal< sc_lv<64> > p_Val2_s_fu_274_p1;
    sc_signal< sc_lv<53> > p_Result_s_fu_292_p3;
    sc_signal< sc_lv<12> > tmp_i_i_i_cast_fu_303_p1;
    sc_signal< sc_lv<12> > sh_assign_fu_306_p2;
    sc_signal< sc_lv<11> > tmp_i_i_20_fu_320_p2;
    sc_signal< sc_lv<1> > isNeg_fu_312_p3;
    sc_signal< sc_lv<12> > tmp_i_i_cast_fu_325_p1;
    sc_signal< sc_lv<12> > sh_assign_3_fu_329_p3;
    sc_signal< sc_lv<32> > sh_assign_1_i_i_cast_fu_337_p1;
    sc_signal< sc_lv<53> > tmp_55_i_i_cast_fu_345_p1;
    sc_signal< sc_lv<112> > tmp_i_i_fu_299_p1;
    sc_signal< sc_lv<112> > tmp_55_i_i_fu_341_p1;
    sc_signal< sc_lv<53> > tmp_56_i_i_fu_349_p2;
    sc_signal< sc_lv<1> > tmp_47_fu_361_p3;
    sc_signal< sc_lv<112> > tmp_57_i_i_fu_355_p2;
    sc_signal< sc_lv<8> > tmp_35_fu_369_p1;
    sc_signal< sc_lv<8> > tmp_36_fu_373_p4;
    sc_signal< sc_lv<31> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<31> ap_ST_fsm_state1;
    static const sc_lv<31> ap_ST_fsm_state2;
    static const sc_lv<31> ap_ST_fsm_state3;
    static const sc_lv<31> ap_ST_fsm_state4;
    static const sc_lv<31> ap_ST_fsm_state5;
    static const sc_lv<31> ap_ST_fsm_state6;
    static const sc_lv<31> ap_ST_fsm_state7;
    static const sc_lv<31> ap_ST_fsm_state8;
    static const sc_lv<31> ap_ST_fsm_state9;
    static const sc_lv<31> ap_ST_fsm_state10;
    static const sc_lv<31> ap_ST_fsm_state11;
    static const sc_lv<31> ap_ST_fsm_state12;
    static const sc_lv<31> ap_ST_fsm_state13;
    static const sc_lv<31> ap_ST_fsm_state14;
    static const sc_lv<31> ap_ST_fsm_state15;
    static const sc_lv<31> ap_ST_fsm_state16;
    static const sc_lv<31> ap_ST_fsm_state17;
    static const sc_lv<31> ap_ST_fsm_state18;
    static const sc_lv<31> ap_ST_fsm_state19;
    static const sc_lv<31> ap_ST_fsm_state20;
    static const sc_lv<31> ap_ST_fsm_state21;
    static const sc_lv<31> ap_ST_fsm_state22;
    static const sc_lv<31> ap_ST_fsm_state23;
    static const sc_lv<31> ap_ST_fsm_state24;
    static const sc_lv<31> ap_ST_fsm_state25;
    static const sc_lv<31> ap_ST_fsm_state26;
    static const sc_lv<31> ap_ST_fsm_state27;
    static const sc_lv<31> ap_ST_fsm_state28;
    static const sc_lv<31> ap_ST_fsm_state29;
    static const sc_lv<31> ap_ST_fsm_state30;
    static const sc_lv<31> ap_ST_fsm_state31;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<32> ap_const_lv32_11;
    static const sc_lv<32> ap_const_lv32_16;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<32> ap_const_lv32_1B;
    static const sc_lv<32> ap_const_lv32_1C;
    static const sc_lv<32> ap_const_lv32_1D;
    static const sc_lv<31> ap_const_lv31_0;
    static const sc_lv<42> ap_const_lv42_0;
    static const sc_lv<32> ap_const_lv32_1E;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_12;
    static const sc_lv<32> ap_const_lv32_17;
    static const sc_lv<64> ap_const_lv64_3FBD2F1A9FBE76C9;
    static const sc_lv<64> ap_const_lv64_3FE2C8B439581062;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<64> ap_const_lv64_3FD322D0E5604189;
    static const sc_lv<42> ap_const_lv42_4B0;
    static const sc_lv<31> ap_const_lv31_1;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_34;
    static const sc_lv<32> ap_const_lv32_3E;
    static const sc_lv<12> ap_const_lv12_C01;
    static const sc_lv<11> ap_const_lv11_3FF;
    static const sc_lv<32> ap_const_lv32_3B;
    // Thread declarations
    void thread_ap_var_for_const0();
    void thread_ap_var_for_const1();
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state18();
    void thread_ap_CS_fsm_state19();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state23();
    void thread_ap_CS_fsm_state24();
    void thread_ap_CS_fsm_state28();
    void thread_ap_CS_fsm_state29();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state30();
    void thread_ap_CS_fsm_state31();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_col_4_fu_218_p2();
    void thread_col_cast_fu_209_p1();
    void thread_grp_fu_157_p0();
    void thread_grp_fu_157_p1();
    void thread_grp_fu_161_p0();
    void thread_grp_fu_161_p1();
    void thread_grp_fu_172_p0();
    void thread_grp_fu_175_p0();
    void thread_imINPUT_address0();
    void thread_imINPUT_ce0();
    void thread_imOUTPUT_address0();
    void thread_imOUTPUT_ce0();
    void thread_imOUTPUT_d0();
    void thread_imOUTPUT_we0();
    void thread_isNeg_fu_312_p3();
    void thread_loc_V_3_fu_288_p1();
    void thread_next_mul_fu_188_p2();
    void thread_p_Result_s_fu_292_p3();
    void thread_p_Val2_s_fu_274_p1();
    void thread_result_V_fu_383_p3();
    void thread_row_4_fu_203_p2();
    void thread_row_cast_fu_194_p1();
    void thread_sh_assign_1_i_i_cast_fu_337_p1();
    void thread_sh_assign_3_fu_329_p3();
    void thread_sh_assign_fu_306_p2();
    void thread_tmp_18_fu_213_p2();
    void thread_tmp_20_cast_fu_262_p1();
    void thread_tmp_29_cast_fu_270_p1();
    void thread_tmp_33_fu_228_p2();
    void thread_tmp_35_fu_369_p1();
    void thread_tmp_36_fu_373_p4();
    void thread_tmp_39_cast_fu_233_p1();
    void thread_tmp_40_fu_184_p1();
    void thread_tmp_43_fu_224_p1();
    void thread_tmp_44_fu_238_p1();
    void thread_tmp_47_fu_361_p3();
    void thread_tmp_55_i_i_cast_fu_345_p1();
    void thread_tmp_55_i_i_fu_341_p1();
    void thread_tmp_56_i_i_fu_349_p2();
    void thread_tmp_57_i_i_fu_355_p2();
    void thread_tmp_fu_198_p2();
    void thread_tmp_i_i_20_fu_320_p2();
    void thread_tmp_i_i_cast_fu_325_p1();
    void thread_tmp_i_i_fu_299_p1();
    void thread_tmp_i_i_i_cast_fu_303_p1();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
